---
abstract: 'Terminate processes if they grow too large'
author:
  - 'Audrey Tang <cpan@audreyt.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Plack::Middleware::SizeLimit
name: Plack-Middleware-SizeLimit
no_index:
  directory:
    - inc
    - t
requires:
  Plack::Middleware: 0
  Process::SizeLimit::Core: '0.9501'
  parent: 0
  perl: 5.8.0
resources:
  homepage: https://github.com/audreyt/plack-middleware-sizelimit/tree
  repository: git://github.com/audreyt/plack-middleware-sizelimit.git
version: '0.09'
